filter:
 excluded_paths:
  - includes/admin_*.php
  - includes/center.php
  - includes/comments.php
  - includes/contents.php
  - includes/generate.php
  - includes/get.php
  - includes/head.php
  - includes/loader.php
  - includes/login.php
  - includes/migrate.php
  - includes/navigation.php
  - includes/password.php
  - includes/query.php
  - includes/registration.php
  - includes/reminder.php
  - includes/replace.php
  - includes/search.php
  - includes/startup.php
  - modules/archive
  - modules/contact
  - modules/db_backup
  - modules/debug
  - modules/fb_group
  - modules/feed_generator
  - modules/feed_reader
  - modules/file_manager
  - modules/gallery
  - modules/get_file
  - modules/github_tracker
  - modules/lazy_load
  - modules/recent_view
  - modules/sitemap
  - modules/sitemap_xml
	
tools:
 external_code_coverage: true
 php_analyzer: true
 php_cpd: true
 php_hhvm: true
 php_loc: true
 php_mess_detector: true
 php_pdepend: true
 sensiolabs_security_checker: true
