filter:
 excluded_paths:
  - includes/admin_admin.php
  - includes/admin_list.php
  - includes/admin_query.php
  - includes/admin_router.php
  - includes/comments.php
  - includes/contents.php
  - includes/head.php
  - includes/loader.php
  - includes/login.php
  - includes/navigation.php
  - includes/query.php
  - includes/registration.php
  - includes/reminder.php
  - includes/router.php
  - includes/search.php
  - includes/startup.php
  - install.php

tools:
 external_code_coverage: true
 php_analyzer: true
 php_cpd: true
 php_hhvm: true
 php_loc: true
 php_mess_detector: true
 php_pdepend: true
 sensiolabs_security_checker: true
