filter:
 excluded_paths:
  - includes/admin_*.php
  - includes/center.php
  - includes/comments.php
  - includes/contents.php
  - includes/generate.php
  - includes/get.php
  - includes/head.php
  - includes/loader.php
  - includes/login.php
  - includes/migrate.php
  - includes/navigation.php
  - includes/password.php
  - includes/query.php
  - includes/registration.php
  - includes/reminder.php
  - includes/replace.php
  - includes/search.php
  - includes/startup.php
  - modules/archive/*.php
  - modules/contact/*.php
  - modules/db_backup/*.php
  - modules/debug/*.php
  - modules/fb_group/*.php
  - modules/feed_generator/*.php
  - modules/feed_reader/*.php
  - modules/file_manager/*.php
  - modules/gallery/*.php
  - modules/get_file/*.php
  - modules/github_tracker/*.php
  - modules/lazy_load/*.php
  - modules/recent_view/*.php
  - modules/sitemap/*.php
  - modules/sitemap_xml/*.php
  - index.php
  - install.php

tools:
 external_code_coverage: true
 php_analyzer: true
 php_cpd: true
 php_hhvm: true
 php_loc: true
 php_mess_detector: true
 php_pdepend: true
 sensiolabs_security_checker: true
