language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0

before_install:
- if [ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]; then composer require phpunit/phpunit 4.8.23 --no-update --dev; fi

install:
- composer self-update
- composer install --ignore-platform-reqs
- gem install mailcatcher
- npm install
- npm install --global grunt-cli

before_script:
- echo sendmail_path=/usr/bin/env catchmail --smtp-ip 127.0.0.1 --smtp-port 1025 -f test@test.com >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
- mailcatcher
- npm test
- npm run phpunit

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
 irc:
  - chat.freenode.net#redaxscript
 webhooks:
  - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
