language: php

php:
- 5.3
- 5.4
- 5.5

before_script:
- npm install -g grunt-cli
- composer self-update
- COMPOSER_PROCESS_TIMEOUT=600 composer install

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml
