language: php

php:
- 5.3
- 5.4

before_script:
- npm install -g grunt-cli
- composer self-update
- composer install

script:
- npm test

after_script:
- php vendor/bin/coveralls --exclude-no-stmt --verbose