language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- nightly

matrix:
 fast_finish: true
 allow_failures:
 - php: nightly

services:
- mysql
- postgresql

before_install:
- if [ ${TRAVIS_PHP_VERSION:0:1} == "5" ]; then composer require brianium/paratest 0.13.3 johnkary/phpunit-speedtrap 1.0.1 phpunit/phpunit 4.8.35 sebastian/phpcpd 2.0.4 phpunit/phpcov 2.0.2 --dev --no-update; fi
- if [ ${TRAVIS_PHP_VERSION:0:1} != "7" ]; then composer remove phpstan/phpstan --dev --no-update; fi
- composer global require hirak/prestissimo

install:
- sudo apt-get update
- sudo apt-get install libxml2-dev
- composer self-update
- composer install
- gem install mime-types -v 2.6.2
- gem install mailcatcher
- nvm install 7
- npm install --global grunt-cli
- npm install

before_script:
- echo sendmail_path=/usr/bin/env catchmail --smtp-ip 127.0.0.1 --smtp-port 1025 -f test@test.com >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- mysql -u root -e 'create database test'
- mysqladmin -u root password test
- psql -U postgres -c 'create database test'
- psql -U postgres -c 'alter user postgres with password '\'test\'
- mkdir build

script:
- grunt
- mailcatcher
- DB_URL=mysql://root:test@127.0.0.1/test grunt phpunit --coverage-clover=build/mysql.xml
- DB_URL=postgres://postgres:test@127.0.0.1/test grunt phpunit --coverage-clover=build/pgsql.xml
- DB_URL=sqlite://test.sqlite grunt phpunit --coverage-clover=build/sqlite.xml

after_success:
- vendor/bin/coveralls -v
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover build/sqlite.xml

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
