language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6

before_script:
- composer self-update
- composer install
- npm install -g grunt-cli
- travis_retry npm install

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml

deploy:
 provider: heroku
 app: redaxscript
 api: TjuQ86X7x2okykATfa04KxadkxxXgnHVaB509unw6193i4xkbqkJXGUh9PHdraBWbhPPHbZAFFL1Sujjosn3CYP2bpWPxqYuODyR9bTvIXPhAoioAKcoLVMgyT0eBaea4YgFfH0nRi2KbO/bBZzPn53oI/8shuT4a/Zut7FLNzc=

notifications:
 irc:
  - chat.freenode.net#redaxscript
