language: php

php:
- 5.3
- 5.4
- 5.5

before_script:
- composer self-update
- composer install
- npm install -g grunt-cli
- npm install grunt
- npm install
- npm install grunt-contrib-copy
- npm install grunt-contrib-csslint
- npm install grunt-contrib-jshint
- npm install grunt-htmlhint
- npm install grunt-jsonlint
- npm install grunt-phpcs
- npm install grunt-phpunit
- npm install grunt-lineending
- npm install grunt-shell

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml
