language: php

php:
- 5.3

before_script:
- composer self-update
- composer install
- npm install --global grunt-cli
- npm install --no-optional

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml
