language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6

env:
 global:
 - secure: Nt4/0gNNA5ZD2t9sCFI4RN0CXL1G0G8hbYv6aQKDI/pY0y55hUpdi0ubW6UOJW1IgRlKxmhVVnOeiTtAe+5dn4fj1HAoMgzUBrYTu9eJUzQg0YUGT7MXLn4qvG3MUD8JuWbuhIEzMmoqKZ1JJ8VOonyxIoleXC/cRhRdBYfUc0c=

before_script:
- composer self-update
- composer install
- npm install -g grunt-cli
- travis_retry npm install

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml

deploy:
 provider: heroku
 strategy: api
 app: redaxscript

notifications:
 irc:
  - chat.freenode.net#redaxscript
