language: php

php:
- 5.3
- 5.4
- 5.5
- hhvm

node_js:
  - 0.11

before_script:
- composer self-update
- composer install
- node -v
- npm -v
- npm install -g grunt-cli
- npm install htmlhint@0.9.3
- npm install

script:
- npm test

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml
